### PR TITLE
Calender, RadioButton, SearchBox

### PR DESCRIPTION
**Pull request by Frank67618**
Calender with datetime picker
RadioButton for BFUcommandbar button
Searchbox

### CODE REVIEW

**Comment by vnbaaij** [comment]
Hi @Frank67618 ,

Love the Searchbox. Only thing not clear to me is how you can 'bind' to a value being selected from the list. Do you have an example of that?

I understand how you have done it for the ContextualMenuItem example, but can't figure out how to do it for a simple string for example. Like show the selected string in a Label or something like that.

**Comment by vnbaaij** [comment]
Ok, I figured out how to do this. It required some changes and additions to SearchBox.razor.cs which you can find in my fork at https://github.com/vnbaaij/BlazorFluentUI/commit/419db78974851ce0fa88b4d363753f3444222c17

**Comment by Frank67618** [comment]
Hello vnbaaji,
ok, I see now what was missing.  Maybe you can also pull request this to the main branch in order to get available for the community?

**Comment by vnbaaij** [comment]
The changes are in my fork. I'll post a PR when I hear from @limefrogyank if he wants to include my changes

**Comment by vnbaaij** [comment]
@Frank67618 I added the bind-SelecteItem and bind-SelectedItems changes to the master branch

**Pull request merged**
