### PR TITLE
Implementation of the DocumentCard control

### PR DESCRIPTION
**Pull request by sebfischer83**
Hi,

this is my try for the DocumentCard control.

### CODE REVIEW

**Comment by limefrogyank** [comment]
This is a pretty good start!  Thanks!  

Just from quickly looking over it, I noticed some things were not implemented yet:

- ShouldTruncate on DocumentCardTitle doesn't work yet
- Focus styles are not implemented (keyboard navigation outlines)

Is there anything else you know of?  I want to make a list of what needs to be added so we can work on them later.

**Comment by sebfischer83** [comment]
Thanks for the quick response.
Indeed ShoudlTruncate is missing, I think currently about a way to make it work in a more Blazor way instead of implemneting it all in JS.
Focus styles for keyboard? Is it something that isnt directly on the component? Sorry I missed it.

**Comment by limefrogyank** [comment]
It's ok because it's complicated.  It relies on a class set from a global key press and removes the default focus outline and instead draws one that fits FluentUI better.  Also, it works better with FocusZone so you can use arrow keys to navigate.  We created some helper methods to do the styling but they're not easy to notice.

From this section:
image

I can add them in though.

**Comment by sebfischer83** [comment]
I will look into it at the weekend and notice you if I have problems. There will be surely examples in other components to give me an idea.

**Comment by limefrogyank** [comment]
FYI, I like how you used a static dictionary to make the class names strongly typed.  It will make re-implementing the styles whenever Microsoft changes the styling much easier.

**Comment by sebfischer83** [comment]
Thanks, it was born because of laziness to write the class all over again.

**Pull request merged**
