### PR TITLE
Feature ShouldTruncate support in DocumentCard

### PR DESCRIPTION
**Pull request by sebfischer83**
Hi,

my implementation for the ShouldTruncate property.
Maybe there is a "simplier" version but I can`t figure it out.

### CODE REVIEW

**Comment by limefrogyank** [comment]
Close!  But I get multiple lines.  I'll give it a go.  FYI, we're targeting both client-side and server-side so all javascript calls back to .NET have to be async (i.e. invokeMethodAsync)

image

**Comment by limefrogyank** [comment]
Oh, that's odd... when I export the react demo to a CodePen view, it gives me multiple lines, too.

**Comment by limefrogyank** [comment]
Actually this is good.  I'm going to merge your additions, then make the quick change from invokeMethod to invokeMethodAsync.

**Comment by sebfischer83** [comment]
Oh thanks for the changes, sorry I forgot about server side.

**Pull request merged**
