### PR TITLE
** For Review and Feedback ** Choice group

### PR DESCRIPTION
**Pull request by StevenRasmussen**
Initial Implementation for #147

So this is my first pass at the ChoiceGroup component.  It's currently *functioning* (see the new "ChoiceGroupPage" in the demos).

I haven't quite figured out how the styling framework works though.  I've made an initial attempt but I'm missing something.  It looks like when you use the `BFULocalStyle` component, the CSS is getting injected into the DOM, and it appends some numbers to the end of the class names, but the styles are not getting applied to the DOM nodes decorated with the core class name.  If you could help point me in the right direction on how to get that functioning that would be great! Thanks!

### CODE REVIEW

**Comment by limefrogyank** [comment]
BFUTextField would be a good example of seeing how the BFULocalCS component works.  You need to add this to the top of your component:
```
BFULocalCS @bind-Rules="@TextFieldLocalRules" />
```
and then in code-behind, populate the `ICollection<TextFieldLocalRules>` with rules.  The rules are a little different.  You can use `CssStringSelector` inside them.  Instead, you'll have to use `ClassSelector` and specify the name of the class as a string (without the dot).  You can modify the selector using other properties for pseudo classes, etc.  

https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/src/BlazorFluentUI.BFUTextField/BFUTextField.razor.cs#L151

Our pattern (so far) is to call a `CreateLocalCss` method in the `OnInitialized` method.  The rule is created there.  Then, we set the css for that rule in the OnThemeChanged handler.  It runs once on load and then runs again if the theme ever changes.

**Comment by limefrogyank** [comment]
FYI, I'll take a look at this later when I can get some free time.

**Comment by limefrogyank** [comment]
I want to see with the styles applied but it looks pretty good so far.  I would probably add a `RenderFragment ItemTemplate` to the `IChoiceGroupOption` interface.  This would allow the selective addition of additional content to the choice item... similar to how the react controls do it:
https://developer.microsoft.com/en-us/fluentui#/controls/web/choicegroup

But I like the global `ItemTemplate`, too.  I think we could have both.  And the individual ItemTemplate would override the global one.  I especially like you allow just string lists, too.  Nice work!

**Comment by limefrogyank** [comment]
I guess we also need an `IconName` ana an `ImageSrc` (and the rest that go with it) in the `IChoiceGroupOption` interface.  That way we can do the image and icon versions, too.

**Comment by StevenRasmussen** [comment]
@limefrogyank - Thanks for the feedback!  I think I must still be missing something with regards to the styling... I updated the local CSS to use a collection and updated the component to use the `@bind-Rules` but still a no-go.  I was missing `id` and `styles` attributes which I thought might be the problem but after adding those it's still not working.  I'm specifically working with the `ChoiceGroupOption` component to try and get the label to style correctly.  Once I have that working I was going to work through the styling for the other elements.  If you have any other thoughts they would be much appreciated.

Re `IChoiceGroupOption` interface:  My initial thoughts were to keep that simple so that implementers wouldn't have unused properties... but I can see that adding those properties you suggest might make sense.  My idea for those wanting more customization possibilities was to use the `OptionTemplate` render fragment of the `ChoiceGroupOption`.  I have updated the demo page with another `ChoiceGroup` demonstrating this (although the styling is still terrible):

image

**Comment by limefrogyank** [comment]
Ahhh, I forgot one thing.  You have to put a reference of the rule into the class or ClassName field of your element or component.

If your rule is called "MyRule", then you'd put `MyRule.Selector.SelectorName` into the class field.

**Comment by limefrogyank** [comment]
Ah, another error on my part.  `OnThemeChanged` is not fired at the start.  You'll have to set the initial style somewhere in the lifecycle that satisfies what you need it to do.  `BFUText` does it in the `OnInitialized` method and also in the `OnThemeChanged` handler.

**Comment by StevenRasmussen** [comment]
@limefrogyank - Thanks!  I've got it working now with styles for the simplest example. I've updated the PR with the changes.  I still need to work out the more complex styling with an image/icon/custom content and being disabled.

**Comment by StevenRasmussen** [comment]
@limefrogyank - I think the component is ready for some testing. I still have a couple of things to refactor but the demo page has everything working properly as far as I can tell.  The interesting thing is that I was waiting until I had all the styling correct before trying to figure out which styles needed to be "local" and update based on a theme change... so I haven't really implemented any "local" styles but the dark theme just works when you hit the toggle.  Here's a screenshot for you:
image

**Comment by limefrogyank** [comment]
It looks really good! Thanks.

A few quirks:

1.  Oddly, if I pick an option in the first set, everything works fine.  If I pick an option in the second sent, the first set mirrors that option.  

2.  For the demo, it may be nice to make the selected month actually be selectable.  You may have to include a `@bind-SelectedKey=@monthKey` in the Dropdown and a `ItemKey=@context.Name` in the DropdownItem.  

FYI, I realize our `Dropdown` positioning is broken.  Somewhere along the line we broke it... I'll have to find out what's wrong.

**Comment by limefrogyank** [comment]
I was looking through the code and I noticed you used a static variable for the purposes of creating a unique id for each input tag.  First, somehow it's not working.  The reason (I think) the second choice group is affecting the first choice group is that they use the same ids.  Second, static variables in serverside Blazor cause problems because the static state is shared with all sessions.  It's probably not a big deal in this case, but I've avoided using static variables because of this.

**Comment by StevenRasmussen** [comment]
Thanks for taking a look!  Regarding the quirks:  I had just noticed that as well and came to the same conclusion regarding the `Id` not working somehow.  I had used this concept before and it seemed to work but not sure what's going on here.  Regardless, you're correct about Blazor server and so I'll remove the static variable.  I have mostly been focusing on Blazor WASM but should certainly consider server side for components like this.

I'll get the date and month components hooked up on the demo page so that they persist when chosen.

FYI - I noticed that the `font-weight` for `Label`'s was not correct and so I have included that fix as part of this PR, along with an improvement to allow setting the `Id` for a label.  This is necessary in order to be able to use the `aria-labelledby` attribute on a parent element which makes a reference to the `Label` id.  Let me know if you'd rather these changes be in a separate PR and I can look at extracting them.

**Comment by limefrogyank** [comment]
Sounds good.  Label was probably one of the very first components I made and so didn't really have a good vision for how it would be used.

**Comment by StevenRasmussen** [comment]
Ok.  Things should be working as expected now. Let me know if you find anything else.

**Comment by limefrogyank** [comment]
This looks really good now.  Thanks!

**Pull request merged**
